### ISSUE TITLE
Add user & link counter in homepage

### ISSUE THREAD

**Issue by mazipan** [mazipan/ksana.in#16]
Add counter how many user already registered and how many shortlink already created in homepage to show the growth and the positioning.

- [x] Urls - done in #19 
- [ ] User -- still not found any docs to select the user count

**Comment by mazipan** [comment]
Close for now, since still have no idea how to get the count of users

**Comment by bramaudi** [comment]
How about creating something like `users` table, then in the login page do checking if user is already exists or not in that table by their `auth.id`.

It's seem to be best approach in my opinion (probably, for now 🤔), even we can add user editable data in there like name, avatar, or anything else.

**Comment by mazipan** [comment]
Yes, from Supabase docs also recommend us to create like a profile table instead of direct from users table which is private and can not be counted directly.

I just afraid this is overkill for now.
Since the feature is not that important, it just nice to have.

But if you can help me on this, maybe we can do that.
If No, I will not doing anything in this ticket.

**Comment by bramaudi** [comment]
Perhaps not really overkill if we creating profile table only for counting purpose isn't it.

Sure, will help on my free time.
