### ISSUE TITLE
Share on desktop

### ISSUE THREAD

**Issue by mazipan** [mazipan/ksana.in#21]
Currently we utilize the Web Share API which is not available on most of desktop browsers.

Need to add manual way to share URL when accessing from desktop device.

Maybe looking for some `react-social-share`, is it available?

**Comment by svspicious** [comment]
My proposal is something like this

![image](https://user-images.githubusercontent.com/35674157/122632555-a7799b00-d0fd-11eb-917c-679697e8722f.png)

the idea is check if `navigator.share` is available if not then fallback using chakra [popover](https://chakra-ui.com/docs/overlay/popover)

like I did in https://edufair-online-prototype-am3uxd9iz.vercel.app/kampus/EupZelxuvAOmyOeU7IUH

or do you have any suggestion 🤔

**Comment by mazipan** [comment]
For me share to Twitter and WhatsApp is enough for starting.
Let me know if you can work on this issue.
Or can you guide me to the sample of code in how you implement this feature, maybe I can learn from it directly

**Comment by svspicious** [comment]
I can work on this 😀

**Comment by mazipan** [comment]
Cool, let me know if you facing any issues when setting up the project on your local.
If you need a Supabase key for development, please DM me on Twitter https://twitter.com/Maz_Ipan, I have a different account for development purpose, you can use it for temporary, or you can just register by yourself, it's free

**Comment by svspicious** [comment]
Supabase pretty easy to setup actually.
And this app just needs one table (right? 🤔)
