### ISSUE TITLE
[UI] Unexpected UI for kebijakan privasi and ketentuan layanan page

### ISSUE THREAD

**Issue by adjieguntoro-tokped** [mazipan/ksana.in#34]
**Describe the bug**
I found that two pages are having unexpected styling, they are kebijakan privasi and ketentuan layanan page

**To Reproduce**

1. Go to 'https://ksana.in/'
2. Click on 'ketentuan layanan' or 'kebijakan privasi' on footer menus
3. Scroll down to 'middle of pages'

**Expected behavior**
A clear and readable page content.

**Screenshots**

![image](https://user-images.githubusercontent.com/37526430/122651585-096ceb80-d164-11eb-9c20-7320d9b2dd50.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome
- Version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mazipan** [comment]
Close on commit https://github.com/mazipan/ksana.in/commit/0438804c545406211e41d72d5c98edc8c34f07d2
